name: Blueprint
options:
  bundleIdPrefix: com.kazakago.blueprint
  deploymentTarget:
    iOS: 15.0
configs:
  Develop-Debug: debug
  Develop-Release: release
  Production-Debug: debug
  Production-Release: release
schemes:
  Develop:
    build:
      targets:
        Blueprint: all
    run:
      config: Develop-Debug
    test:
      config: Develop-Debug
      targets:
        - BlueprintTests
        - BlueprintUITests
        - Presentation_ControllerTests
        - Presentation_UiTests
        - Presentation_UiStateTests
        - Presentation_ViewModelTests
        - Domain_UseCaseTests
        - Domain_ModelTests
        - Domain_RepositoryTests
        - Data_RepositoryTests
        - Data_MapperTests
        - Data_ApiTests
        - Data_CacheTests
        - Data_ResourceTests
    profile:
      config: Develop-Release
    analyze:
      config: Develop-Debug
    archive:
      config: Develop-Release
  Production:
    build:
      targets:
        Blueprint: all
    run:
      config: Production-Debug
    test:
      config: Production-Debug
      targets:
        - BlueprintTests
        - BlueprintUITests
        - Presentation_ControllerTests
        - Presentation_UiTests
        - Presentation_UiStateTests
        - Presentation_ViewModelTests
        - Domain_UseCaseTests
        - Domain_ModelTests
        - Domain_RepositoryTests
        - Data_RepositoryTests
        - Data_MapperTests
        - Data_ApiTests
        - Data_CacheTests
        - Data_ResourceTests
    profile:
      config: Production-Release
    analyze:
      config: Production-Debug
    archive:
      config: Production-Release
targets:
  Blueprint:
    type: application
    platform: iOS
    sources:
      - path: Blueprint
    dependencies:
      - target: Presentation_Controller
      - target: Presentation_Ui
      - target: Presentation_UiState
      - target: Presentation_ViewModel
      - target: Domain_UseCase
      - target: Domain_Model
      - target: Domain_Repository
      - target: Data_Repository
      - target: Data_Mapper
      - target: Data_Api
      - target: Data_Cache
      - target: Data_Resource
      - package: StoreFlowable
      - package: Swinject
    info:
      path: Blueprint/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest: {
          UIApplicationSupportsMultipleScenes: true
        }
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities: [armv7]
        UISupportedInterfaceOrientations: [
          UIInterfaceOrientationPortrait,
          UIInterfaceOrientationLandscapeLeft,
          UIInterfaceOrientationLandscapeRight,
        ]
        UISupportedInterfaceOrientations~ipad: [
          UIInterfaceOrientationPortrait,
          UIInterfaceOrientationPortraitUpsideDown,
          UIInterfaceOrientationLandscapeLeft,
          UIInterfaceOrientationLandscapeRight,
        ]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kazakago.blueprint
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: 3WUM9V6RP7
      configs:
        Develop-Debug:
          PROVISIONING_PROFILE_SPECIFIER: match Development *
          CODE_SIGN_IDENTITY: Apple Development
        Develop-Release:
          PROVISIONING_PROFILE_SPECIFIER: match AdHoc *
          CODE_SIGN_IDENTITY: Apple Distribution
        Production-Debug:
          PROVISIONING_PROFILE_SPECIFIER: match Development *
          CODE_SIGN_IDENTITY: Apple Development
        Production-Release:
          PROVISIONING_PROFILE_SPECIFIER: match AdHoc *
          CODE_SIGN_IDENTITY: Apple Distribution
  BlueprintTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BlueprintTests
    dependencies:
      - target: Blueprint
    info:
      path: BlueprintTests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  BlueprintUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: BlueprintUITests
    dependencies:
      - target: Blueprint
    info:
      path: BlueprintUITests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Presentation_Controller:
    type: framework
    platform: iOS
    sources:
      - path: Presentation_Controller
    dependencies:
      - target: Presentation_Ui
      - target: Presentation_UiState
      - target: Presentation_ViewModel
      - target: Domain_Model
      - package: Swinject
    info:
      path: Presentation_Controller/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Presentation_ControllerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Presentation_ControllerTests
    dependencies:
      - target: Blueprint
    info:
      path: Presentation_ControllerTests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Presentation_Ui:
    type: framework
    platform: iOS
    sources:
      - path: Presentation_Ui
    dependencies:
      - target: Presentation_UiState
      - target: Domain_Model
    info:
      path: Presentation_Ui/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Presentation_UiTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Presentation_UiTests
    dependencies:
      - target: Blueprint
    info:
      path: Presentation_UiTests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Presentation_UiState:
    type: framework
    platform: iOS
    sources:
      - path: Presentation_UiState
    dependencies:
      - target: Domain_Model
    info:
      path: Presentation_UiState/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Presentation_UiStateTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Presentation_UiStateTests
    dependencies:
      - target: Blueprint
    info:
      path: Presentation_UiStateTests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Presentation_ViewModel:
    type: framework
    platform: iOS
    sources:
      - path: Presentation_ViewModel
    dependencies:
      - target: Domain_UseCase
      - target: Domain_Model
      - package: StoreFlowable
      - package: Swinject
    info:
      path: Presentation_ViewModel/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Presentation_ViewModelTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Presentation_ViewModelTests
    dependencies:
      - target: Blueprint
    info:
      path: Presentation_ViewModelTests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Domain_UseCase:
    type: framework
    platform: iOS
    sources:
      - path: Domain_UseCase
    dependencies:
      - target: Domain_Model
      - target: Domain_Repository
      - package: StoreFlowable
      - package: Swinject
    info:
      path: Domain_UseCase/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Domain_UseCaseTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Domain_UseCaseTests
    dependencies:
      - target: Blueprint
    info:
      path: Domain_UseCaseTests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Domain_Model:
    type: framework
    platform: iOS
    sources:
      - path: Domain_Model
    info:
      path: Domain_Model/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Domain_ModelTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Domain_ModelTests
    dependencies:
      - target: Blueprint
    info:
      path: Domain_ModelTests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Domain_Repository:
    type: framework
    platform: iOS
    sources:
      - path: Domain_Repository
    dependencies:
      - target: Domain_Model
      - package: StoreFlowable
    info:
      path: Domain_Repository/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Domain_RepositoryTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Domain_RepositoryTests
    dependencies:
      - target: Blueprint
    info:
      path: Domain_RepositoryTests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Data_Repository:
    type: framework
    platform: iOS
    sources:
      - path: Data_Repository
    dependencies:
      - target: Domain_Model
      - target: Domain_Repository
      - target: Data_Mapper
      - target: Data_Api
      - target: Data_Cache
      - target: Data_Resource
      - package: StoreFlowable
      - package: Swinject
    info:
      path: Data_Repository/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Data_RepositoryTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Data_RepositoryTests
    dependencies:
      - target: Blueprint
    info:
      path: Data_RepositoryTests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Data_Mapper:
    type: framework
    platform: iOS
    sources:
      - path: Data_Mapper
    dependencies:
      - target: Domain_Model
      - target: Data_Api
      - target: Data_Cache
      - target: Data_Resource
      - package: Swinject
    info:
      path: Data_Mapper/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Data_MapperTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Data_MapperTests
    dependencies:
      - target: Blueprint
    info:
      path: Data_MapperTests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Data_Api:
    type: framework
    platform: iOS
    sources:
      - path: Data_Api
    dependencies:
      - package: Alamofire
      - package: Swinject
    info:
      path: Data_Api/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Data_ApiTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Data_ApiTests
    dependencies:
      - target: Blueprint
    info:
      path: Data_ApiTests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Data_Cache:
    type: framework
    platform: iOS
    sources:
      - path: Data_Cache
    dependencies:
      - package: StoreFlowable
      - package: Swinject
    info:
      path: Data_Cache/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Data_CacheTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Data_CacheTests
    dependencies:
      - target: Blueprint
    info:
      path: Data_CacheTests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Data_Resource:
    type: framework
    platform: iOS
    sources:
      - path: Data_Resource
    dependencies:
      - package: Swinject
    info:
      path: Data_Resource/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  Data_ResourceTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Data_ResourceTests
    dependencies:
      - target: Blueprint
    info:
      path: Data_ResourceTests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
packages:
  Swinject:
    url: https://github.com/Swinject/Swinject.git
    from: 2.0.0
  StoreFlowable:
    url: https://github.com/KazaKago/StoreFlowable.swift.git
    from: 4.0.0
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.0.0
